version: '3'
services: 
  app:
    image: deployment/guide
    container_name: deployment_guide
    build:
      context: .
    ports:
     - 5000:80
    environment: 
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: http://+:80;